# import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
# import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/ayu_light.toml"]
[env]
TERM = "xterm-256color"


[window]
option_as_alt = "Both"

[font]
offset.y =8 
size = 16
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
